version: "3"
services:
  eureka:
    build: ./eureka_server
    image: yunterry/eureka
    ports:
      - 8761:8761

  consumer:
    build: ./feign
    image: yunterry/feign-consumer
    ports:
      - 3000
    links:
      - eureka

  gateway:
    build: ./zuul
    image: yunterry/zuul-gateway
    ports:
      - 4000
    links:
      - eureka
